import * as d3 from "d3";
import { feature, mesh } from "topojson-client";
import "./style.css";

type ProjectionName = "mercator" | "azimuthal" | "equalEarth" | "orthographic" | "equirectangular";
type Lang = "ja" | "en";
type ThemeName = "classic" | "cyber" | "military" | "nature" | "paper";
type LayerKey = "borders" | "cities" | "standardGrid" | "axisGrid" | "axis" | "circles" | "routes" | "tissot";
type Point = { name: string; coord: [number, number] };

type AppState = {
  projection: ProjectionName; lng: number; lat: number; roll: number; scale: number;
  lang: Lang; theme: ThemeName; layers: Record<LayerKey, boolean>;
};

const themes = {
  classic: { bg: "#363636", sea: "#4a7d7f", land: "#a5a278", border: "#555", accent: "#fff", grid: "rgba(255,255,255,.2)", circle: "rgba(255,255,255,.45)", panel: "rgba(54,54,54,.96)" },
  cyber: { bg: "#000", sea: "#000510", land: "#1c2128", border: "#444c56", accent: "#48d1cc", grid: "rgba(72,209,204,.16)", circle: "rgba(72,209,204,.5)", panel: "rgba(22,27,34,.96)" },
  military: { bg: "#000", sea: "#000", land: "#2d3319", border: "#556622", accent: "#ffb74d", grid: "rgba(255,183,77,.16)", circle: "rgba(255,183,77,.55)", panel: "rgba(26,26,0,.96)" },
  nature: { bg: "#203a32", sea: "#5d8aa8", land: "#8fbc8f", border: "rgba(255,255,255,.45)", accent: "#fff", grid: "rgba(255,255,255,.18)", circle: "rgba(255,255,255,.45)", panel: "rgba(30,50,40,.96)" },
  paper: { bg: "#f0f0f0", sea: "#e0e0e0", land: "#fff", border: "#999", accent: "#111", grid: "rgba(0,0,0,.08)", circle: "rgba(211,47,47,.45)", panel: "rgba(255,255,255,.96)" },
} as const;

const cities: Point[] = [
  ["Null Island", 0, 0], ["North Pole", 0, 89.9], ["South Pole", 0, -89.9],
  ["Tokyo", 139.76, 35.68], ["Osaka", 135.5, 34.69], ["Sapporo", 141.35, 43.06], ["Fukuoka", 130.4, 33.59], ["Seoul", 126.97, 37.56], ["Beijing", 116.4, 39.9], ["Shanghai", 121.47, 31.23], ["Hong Kong", 114.17, 22.31], ["Taipei", 121.56, 25.03], ["Ulaanbaatar", 106.88, 47.88], ["Pyongyang", 125.75, 39.02],
  ["Singapore", 103.81, 1.35], ["Bangkok", 100.5, 13.75], ["Jakarta", 106.84, -6.2], ["Manila", 120.98, 14.59], ["Kuala Lumpur", 101.68, 3.13], ["Ho Chi Minh City", 106.66, 10.76], ["Delhi", 77.21, 28.61], ["Mumbai", 72.88, 19.07], ["Dhaka", 90.41, 23.81], ["Sydney", 151.2, -33.86], ["Melbourne", 144.96, -37.81], ["Perth", 115.86, -31.95], ["Auckland", 174.76, -36.84],
  ["London", -0.12, 51.5], ["Paris", 2.35, 48.85], ["Berlin", 13.4, 52.52], ["Rome", 12.49, 41.9], ["Madrid", -3.7, 40.41], ["Amsterdam", 4.89, 52.37], ["Vienna", 16.37, 48.2], ["Zurich", 8.54, 47.37], ["Stockholm", 18.06, 59.32], ["Moscow", 37.61, 55.75], ["Istanbul", 28.97, 41], ["Athens", 23.73, 37.98], ["Lisbon", -9.14, 38.72], ["Oslo", 10.75, 59.91], ["Helsinki", 24.94, 60.17], ["Warsaw", 21.01, 52.23],
  ["New York", -74, 40.71], ["Washington DC", -77.03, 38.9], ["Chicago", -87.62, 41.87], ["Los Angeles", -118.24, 34.05], ["San Francisco", -122.41, 37.77], ["Toronto", -79.38, 43.65], ["Vancouver", -123.12, 49.28], ["Mexico City", -99.13, 19.43], ["Havana", -82.37, 23.11], ["Bogota", -74.07, 4.71], ["Lima", -77.04, -12.05], ["Santiago", -70.66, -33.44], ["São Paulo", -46.63, -23.55], ["Buenos Aires", -58.38, -34.6], ["Rio de Janeiro", -43.17, -22.91],
  ["Cairo", 31.23, 30.04], ["Lagos", 3.37, 6.52], ["Johannesburg", 28.04, -26.2], ["Nairobi", 36.82, -1.29], ["Cape Town", 18.42, -33.92], ["Addis Ababa", 38.75, 9.03], ["Dubai", 55.27, 25.2], ["Riyadh", 46.67, 24.71], ["Tehran", 51.38, 35.68], ["Baghdad", 44.37, 33.31], ["Jerusalem", 35.21, 31.77], ["Casablanca", -7.59, 33.57],
].map(([name, lng, lat]) => ({ name: String(name), coord: [Number(lng), Number(lat)] }));

const cityLabelsJa: Record<string, string> = { "Null Island": "ヌル島", "North Pole": "北極", "South Pole": "南極", Tokyo: "東京", Osaka: "大阪", Sapporo: "札幌", Fukuoka: "福岡", Seoul: "ソウル", Beijing: "北京", Shanghai: "上海", "Hong Kong": "香港", Taipei: "台北", Ulaanbaatar: "ウランバートル", Pyongyang: "平壌", Singapore: "シンガポール", Bangkok: "バンコク", Jakarta: "ジャカルタ", Manila: "マニラ", "Kuala Lumpur": "クアラルンプール", "Ho Chi Minh City": "ホーチミン", Delhi: "デリー", Mumbai: "ムンバイ", Dhaka: "ダッカ", Sydney: "シドニー", Melbourne: "メルボルン", Perth: "パース", Auckland: "オークランド", London: "ロンドン", Paris: "パリ", Berlin: "ベルリン", Rome: "ローマ", Madrid: "マドリード", Amsterdam: "アムステルダム", Vienna: "ウィーン", Zurich: "チューリヒ", Stockholm: "ストックホルム", Moscow: "モスクワ", Istanbul: "イスタンブール", Athens: "アテネ", Lisbon: "リスボン", Oslo: "オスロ", Helsinki: "ヘルシンキ", Warsaw: "ワルシャワ", "New York": "ニューヨーク", "Washington DC": "ワシントンD.C.", Chicago: "シカゴ", "Los Angeles": "ロサンゼルス", "San Francisco": "サンフランシスコ", Toronto: "トロント", Vancouver: "バンクーバー", "Mexico City": "メキシコシティ", Havana: "ハバナ", Bogota: "ボゴタ", Lima: "リマ", Santiago: "サンティアゴ", "São Paulo": "サンパウロ", "Buenos Aires": "ブエノスアイレス", "Rio de Janeiro": "リオデジャネイロ", Cairo: "カイロ", Lagos: "ラゴス", Johannesburg: "ヨハネスブルグ", Nairobi: "ナイロビ", "Cape Town": "ケープタウン", "Addis Ababa": "アディスアベバ", Dubai: "ドバイ", Riyadh: "リヤド", Tehran: "テヘラン", Baghdad: "バグダッド", Jerusalem: "エルサレム", Casablanca: "カサブランカ" };
const majorCities = new Set(["Tokyo", "Osaka", "Seoul", "Beijing", "Shanghai", "Singapore", "Bangkok", "Jakarta", "Delhi", "Mumbai", "Sydney", "Melbourne", "London", "Paris", "Berlin", "Rome", "Madrid", "Moscow", "Istanbul", "New York", "Washington DC", "Chicago", "Los Angeles", "San Francisco", "Toronto", "Mexico City", "Bogota", "Lima", "Santiago", "São Paulo", "Buenos Aires", "Cairo", "Lagos", "Johannesburg", "Nairobi", "Cape Town", "Dubai", "Riyadh", "Tehran"]);
const cityRegions: Record<string, string> = { Tokyo: "Japan", Osaka: "Japan", Sapporo: "Japan", Fukuoka: "Japan", Seoul: "East Asia", Beijing: "East Asia", Shanghai: "East Asia", "Hong Kong": "East Asia", Taipei: "East Asia", Ulaanbaatar: "East Asia", Pyongyang: "East Asia", Singapore: "Southeast Asia", Bangkok: "Southeast Asia", Jakarta: "Southeast Asia", Manila: "Southeast Asia", "Kuala Lumpur": "Southeast Asia", "Ho Chi Minh City": "Southeast Asia", Delhi: "South Asia", Mumbai: "South Asia", Dhaka: "South Asia", Sydney: "Oceania", Melbourne: "Oceania", Perth: "Oceania", Auckland: "Oceania", London: "Europe", Paris: "Europe", Berlin: "Europe", Rome: "Europe", Madrid: "Europe", Amsterdam: "Europe", Vienna: "Europe", Zurich: "Europe", Stockholm: "Europe", Moscow: "Europe", Istanbul: "Europe", Athens: "Europe", Lisbon: "Europe", Oslo: "Europe", Helsinki: "Europe", Warsaw: "Europe", "New York": "Americas", "Washington DC": "Americas", Chicago: "Americas", "Los Angeles": "Americas", "San Francisco": "Americas", Toronto: "Americas", Vancouver: "Americas", "Mexico City": "Americas", Havana: "Americas", Bogota: "South America", Lima: "South America", Santiago: "South America", "São Paulo": "South America", "Buenos Aires": "South America", "Rio de Janeiro": "South America", Cairo: "Africa", Lagos: "Africa", Johannesburg: "Africa", Nairobi: "Africa", "Cape Town": "Africa", "Addis Ababa": "Africa", Dubai: "Middle East", Riyadh: "Middle East", Tehran: "Middle East", Baghdad: "Middle East", Jerusalem: "Middle East", Casablanca: "Africa", "Null Island": "Special", "North Pole": "Special", "South Pole": "Special" };
function cityName(city: Point) { return state.lang === "ja" ? cityLabelsJa[city.name] || city.name : city.name; }
function cityRegion(city: Point) { return cityRegions[city.name] || "Other"; }
function isMajorCity(city: Point) { return majorCities.has(city.name) || city.name === "Null Island" || city.name.includes("Pole"); }

const labels = {
  ja: { title: "地図方位スタジオ", projection: "投影法", center: "中心地点", telemetry: "テレメトリ", lng: "経度", lat: "緯度", roll: "ロール", scale: "縮尺", layers: "レイヤー", borders: "国境線", cities: "都市名", standardGrid: "標準グリッド", axisGrid: "斜軸グリッド", axis: "中央軸", circles: "等距離円", routes: "大圏航路", tissot: "歪み指示円", theme: "テーマ", export: "PNG保存", guide: "ドラッグ: 中心移動 / Shift+ドラッグ: 回転 / ホイール: 拡大縮小", loading: "地図データを読み込み中…", error: "地図データを読み込めませんでした。ネットワークを確認してください。", distance: "距離", heading: "方位", search: "都市を検索", cityMode: "都市表示", majorCities: "主要都市のみ", allCities: "全都市", compareCity: "比較地点", comparison: "2地点比較", projectionInfo: "投影法の解説", close: "閉じる", projectionNames: { azimuthal: "正距方位図法", mercator: "メルカトル図法", equalEarth: "Equal Earth図法", orthographic: "正射方位図法", equirectangular: "正距円筒図法" } },
  en: { title: "Map Orientation Studio", projection: "Projection", center: "Center preset", telemetry: "Telemetry", lng: "Longitude", lat: "Latitude", roll: "Roll", scale: "Scale", layers: "Layers", borders: "Borders", cities: "City names", standardGrid: "Standard grid", axisGrid: "Oblique grid", axis: "Central axis", circles: "Distance circles", routes: "Great-circle route", tissot: "Distortion circles", theme: "Theme", export: "Export PNG", guide: "Drag: move center / Shift+drag: rotate / Wheel: zoom", loading: "Loading map data…", error: "Map data could not be loaded. Check your network connection.", distance: "Distance", heading: "Heading", search: "Search cities", cityMode: "City display", majorCities: "Major cities only", allCities: "All cities", compareCity: "Compare point", comparison: "Two-point comparison", projectionInfo: "Projection guide", close: "Close", projectionNames: { azimuthal: "Azimuthal Equidistant", mercator: "Mercator", equalEarth: "Equal Earth", orthographic: "Orthographic", equirectangular: "Equirectangular" } },
} as const;

const state: AppState = { projection: "azimuthal", lng: 139.76, lat: 35.68, roll: 0, scale: 100, lang: "ja", theme: "classic", layers: { borders: true, cities: true, standardGrid: true, axisGrid: true, axis: true, circles: true, routes: false, tissot: false } };
const canvas = document.createElement("canvas");
const context = canvas.getContext("2d")!;
let width = 1, height = 1, world: any, borders: any, projection: d3.GeoProjection;
let pointerStart: { x: number; y: number } | null = null;
const activePointers = new Map<number, { x: number; y: number }>();
let pinchStartDistance: number | null = null;
let pinchStartScale = 100;
let cityQuery = "";
let cityMode: "major" | "all" = "major";
let projectionHelpOpen = false;
let compareCoord: [number, number] = [-74, 40.71];

function projectionFor(name: ProjectionName) {
  if (name === "mercator") return d3.geoMercator();
  if (name === "equalEarth") return d3.geoEqualEarth();
  if (name === "orthographic") return d3.geoOrthographic().clipAngle(90);
  if (name === "equirectangular") return d3.geoEquirectangular();
  return d3.geoAzimuthalEquidistant().clipAngle(179.999);
}
function centerRotation() { return [-state.lng, -state.lat, state.roll] as [number, number, number]; }
function clampState() { state.lng = Math.max(-180, Math.min(180, state.lng)); state.lat = Math.max(-89.9, Math.min(89.9, state.lat)); state.roll = ((state.roll % 360) + 360) % 360; state.scale = Math.max(30, Math.min(900, state.scale)); }
function fitScale() { return ["azimuthal", "orthographic"].includes(state.projection) ? Math.max(35, Math.min(width, height) * .48 / Math.PI) : Math.max(45, width / (2 * Math.PI)); }
function updateProjection() { clampState(); projection = projectionFor(state.projection).translate([width / 2, height / 2]).scale(fitScale() * state.scale / 100).rotate(centerRotation()).precision(.1); }
function pointDistance(a: [number, number], b: [number, number]) { return Math.round(d3.geoDistance(a, b) * 6371); }
function pointerDistance() { const points = [...activePointers.values()]; return points.length === 2 ? Math.hypot(points[0].x - points[1].x, points[0].y - points[1].y) : 0; }
function isCityVisible(city: Point) { if (state.projection === "orthographic" && d3.geoDistance([state.lng, state.lat], city.coord) > Math.PI / 2 + 0.01) return false; return Boolean(projection?.(city.coord)); }
function initialBearing(a: [number, number], b: [number, number]) { const [lon1, lat1, lon2, lat2] = [a[0], a[1], b[0], b[1]].map(d => d * Math.PI / 180); const y = Math.sin(lon2 - lon1) * Math.cos(lat2); const x = Math.cos(lat1) * Math.sin(lat2) - Math.sin(lat1) * Math.cos(lat2) * Math.cos(lon2 - lon1); return (Math.atan2(y, x) * 180 / Math.PI + 360) % 360; }
function comparisonCity() { return cities.find(city => city.coord[0] === compareCoord[0] && city.coord[1] === compareCoord[1]); }
const projectionGuides = { ja: { azimuthal: ["中心からの距離と方位を保つ", "中心から離れるほど外周が大きく伸びる", "航路・中心地点からの距離比較"], mercator: ["角度を保つ", "高緯度ほど面積と距離が大きく伸びる", "航海・世界の概観"], equalEarth: ["面積を保つ", "形と距離は場所により歪む", "統計地図・世界全体の比較"], orthographic: ["地球儀を遠くから見た外観を保つ", "表示半球の外周で大きく歪む。裏側は表示しない", "地球の外観・教材・衛星視点"], equirectangular: ["経度緯度の間隔をそのまま配置", "高緯度で形と面積が歪む", "単純な座標確認・データ下処理"] }, en: { azimuthal: ["Preserves distance and direction from the center", "The outer edge expands strongly", "Routes and center-based distance comparison"], mercator: ["Preserves angles", "Area and distance expand toward the poles", "Navigation and world overviews"], equalEarth: ["Preserves area", "Shape and distance vary by location", "Statistical maps and global comparison"], orthographic: ["Looks like a globe viewed from far away", "The outer edge distorts and the far side is hidden", "Globe views, teaching and satellite-like views"], equirectangular: ["Places longitude and latitude at even intervals", "Shape and area distort at high latitudes", "Simple coordinate inspection"] } } as const;
const orientationGuides = { ja: { center: ["中心は、地図の正面に向ける地点です。正距方位図法では、中心からの距離と方位を読む基準になります。", "東京中心なら東京から見た世界、北極中心なら北極から見た世界になります。航路、通信範囲、地域間の関係を観察するときに役立ちます。"], axis: ["ロールは、中心を正面に向けたまま地図を時計回り・反時計回りに回す角度です。", "北を上に固定しないことで、中心地点から見た前方・左右・上下の関係や、斜めの基準軸を比較できます。"], pole: ["極を中心に設定すると、極から見た経度方向の広がりと、緯度線の集まり方を観察できます。", "北極・南極付近の航路、極域の面積歪み、日付変更線や経度線の連続性を見るときに役立ちます。"] }, en: { center: ["The center is the point facing the viewer. In an azimuthal equidistant map, it is the reference for distance and direction.", "Centering Tokyo shows the world from Tokyo; centering the North Pole shows the world from the pole. This helps inspect routes, reach and regional relationships."], axis: ["Roll rotates the map clockwise or counterclockwise while keeping the center facing you.", "It lets you compare forward, sideways and diagonal relationships without forcing north to remain at the top."], pole: ["Centering a pole reveals how longitude fans out and how latitude circles gather around the pole.", "It is useful for polar routes, high-latitude distortion, the date line and the continuity of meridians."] } } as const;
function persistState() { const params = new URLSearchParams({ projection: state.projection, lng: state.lng.toFixed(2), lat: state.lat.toFixed(2), roll: state.roll.toFixed(1), scale: String(Math.round(state.scale)), lang: state.lang, theme: state.theme, layers: Object.entries(state.layers).filter(([, enabled]) => enabled).map(([key]) => key).join(",") }); history.replaceState(null, "", `${location.pathname}${location.search}#${params}`); }
function restoreState() { const params = new URLSearchParams(location.hash.slice(1)); const projectionNames: ProjectionName[] = ["mercator", "azimuthal", "equalEarth", "orthographic", "equirectangular"]; const projectionValue = params.get("projection"); if (projectionValue && projectionNames.includes(projectionValue as ProjectionName)) state.projection = projectionValue as ProjectionName; for (const key of ["lng", "lat", "roll", "scale"] as const) { const value = Number(params.get(key)); if (Number.isFinite(value)) state[key] = value; } const langValue = params.get("lang"); if (langValue === "en" || langValue === "ja") state.lang = langValue; const themeValue = params.get("theme"); if (themeValue && themeValue in themes) state.theme = themeValue as ThemeName; if (params.has("layers")) { const enabled = new Set((params.get("layers") || "").split(",")); for (const key of Object.keys(state.layers) as LayerKey[]) state.layers[key] = enabled.has(key); } }

function render() {
  if (!world || !projection) return;
  const t = themes[state.theme], path = d3.geoPath(projection, context), graticule = d3.geoGraticule().step([15, 15]);
  context.clearRect(0, 0, width, height); context.fillStyle = t.bg; context.fillRect(0, 0, width, height);
  context.beginPath(); path({ type: "Sphere" }); context.fillStyle = t.sea; context.fill();
  if (state.layers.standardGrid) { context.beginPath(); path(graticule()); context.strokeStyle = t.grid; context.lineWidth = .5; context.stroke(); }
  context.beginPath(); path(world); context.fillStyle = t.land; context.fill();
  if (state.layers.borders) { context.beginPath(); path(borders); context.strokeStyle = t.border; context.lineWidth = .7; context.stroke(); }
  if (state.layers.axisGrid) {
    context.strokeStyle = t.grid; context.lineWidth = .7;
    for (let lng = -180; lng <= 180; lng += 15) { const line = { type: "LineString", coordinates: Array.from({ length: 35 }, (_, i) => [lng, -85 + i * 5]) }; const rotated = { type: "LineString", coordinates: (line.coordinates as [number, number][]).map(c => d3.geoRotation(centerRotation()).invert(c)) }; context.beginPath(); path(rotated as any); context.stroke(); }
  }
  if (state.layers.tissot) { context.strokeStyle = "rgba(255, 90, 90, .65)"; context.lineWidth = .8; for (let lng = -150; lng <= 150; lng += 30) for (let lat = -60; lat <= 60; lat += 30) { const center: [number, number] = [lng, lat]; if (state.projection === "orthographic" && d3.geoDistance([state.lng, state.lat], center) > Math.PI / 2) continue; context.beginPath(); path(d3.geoCircle().center(center).radius(5)()); context.stroke(); } }
  if (state.layers.routes) { const route = { type: "LineString", coordinates: Array.from({ length: 101 }, (_, i) => d3.geoInterpolate([state.lng, state.lat], compareCoord)(i / 100)) }; context.beginPath(); path(route as any); context.strokeStyle = t.accent; context.lineWidth = 2; context.setLineDash([8, 5]); context.stroke(); context.setLineDash([]); }
  if (state.projection === "azimuthal" && state.layers.circles) { context.strokeStyle = t.circle; context.lineWidth = 1.1; context.setLineDash([4, 6]); for (let km = 30; km < 180; km += 30) { context.beginPath(); path(d3.geoCircle().center([state.lng, state.lat]).radius(km)()); context.stroke(); } context.setLineDash([]); }
  if (state.layers.axis) { context.strokeStyle = "#f0f"; context.setLineDash([5, 5]); context.beginPath(); context.moveTo(width / 2, 0); context.lineTo(width / 2, height); context.moveTo(0, height / 2); context.lineTo(width, height / 2); context.stroke(); context.setLineDash([]); }
  if (state.layers.cities) { context.font = `${width < 520 ? 8 : 10}px SF Mono, Menlo, monospace`; context.fillStyle = t.accent; for (const city of cities) { const p = projection(city.coord); if (cityMode === "major" && !isMajorCity(city)) continue; if (!isCityVisible(city) || !p || p[0] <= 0 || p[0] >= width || p[1] <= 0 || p[1] >= height) continue; context.beginPath(); context.arc(p[0], p[1], 2, 0, Math.PI * 2); context.fill(); context.fillText(cityName(city), p[0] + 5, p[1] + 3); } }
  updateInputs(); applyTheme(t); updateReadout(); updateComparisonReadout(); persistState();
}
function applyTheme(t: typeof themes[ThemeName]) { const root = document.documentElement; for (const [key, value] of Object.entries({ bg: t.bg, panel: t.panel, accent: t.accent, border: t.border, text: t.accent })) root.style.setProperty(`--${key}`, value); }
function updateInputs() { $(HTMLInputElement, "lng").value = state.lng.toFixed(2); $(HTMLInputElement, "lat").value = state.lat.toFixed(2); $(HTMLInputElement, "roll").value = state.roll.toFixed(1); $(HTMLInputElement, "scale").value = String(Math.round(state.scale)); }
function updateReadout(coords?: [number, number]) { const t = labels[state.lang]; $("distance").textContent = `${t.distance}: ${coords ? pointDistance([state.lng, state.lat], coords).toLocaleString() : "—"} km`; }
function updateComparisonReadout() { const t = labels[state.lang], city = comparisonCity(), distance = pointDistance([state.lng, state.lat], compareCoord); $("comparison").textContent = `${t.comparison}: ${city ? cityName(city) : compareCoord.join(", ")} / ${distance.toLocaleString()} km / ${Math.round(initialBearing([state.lng, state.lat], compareCoord))}°`; }
function $(id: string): HTMLElement;
function $(ctor: typeof HTMLInputElement, id: string): HTMLInputElement;
function $(first: string | typeof HTMLInputElement, second?: string): HTMLElement { return document.getElementById(typeof first === "string" ? first : second!)!; }
function refreshCityOptions() { const query = cityQuery.trim().toLocaleLowerCase(); const visibleCities = cities.filter(city => (cityMode === "all" || isMajorCity(city)) && (!query || `${city.name} ${cityName(city)} ${cityRegion(city)}`.toLocaleLowerCase().includes(query))); for (const id of ["city", "city-compare"]) { const select = $(id) as HTMLSelectElement; const selected = id === "city-compare" ? JSON.stringify(compareCoord) : select.value; select.replaceChildren(); const groups = new Map<string, HTMLOptGroupElement>(); for (const city of visibleCities) { const region = cityRegion(city); if (!groups.has(region)) { const group = document.createElement("optgroup"); group.label = region; groups.set(region, group); select.appendChild(group); } groups.get(region)!.appendChild(new Option(cityName(city), JSON.stringify(city.coord))); } if ([...select.options].some(option => option.value === selected)) select.value = selected; } }
function renderProjectionHelp() { const t = labels[state.lang], guide = projectionGuides[state.lang][state.projection], concepts = orientationGuides[state.lang]; $("projection-help").innerHTML = `<div class="help-head"><strong>${t.projectionInfo}</strong><button id="close-help" type="button">${t.close}</button></div><h3>${t.projectionNames[state.projection]}</h3><p>${guide[0]}</p><dl><dt>${state.lang === "ja" ? "歪みの傾向" : "Distortion"}</dt><dd>${guide[1]}</dd><dt>${state.lang === "ja" ? "向いている用途" : "Useful for"}</dt><dd>${guide[2]}</dd></dl><div class="concept-block"><h4>${state.lang === "ja" ? "中心" : "Center"} (${state.lng.toFixed(2)}°, ${state.lat.toFixed(2)}°)</h4><p>${concepts.center[0]}</p><p>${concepts.center[1]}</p></div><div class="concept-block"><h4>${state.lang === "ja" ? "軸・ロール" : "Axis / roll"} (${state.roll.toFixed(1)}°)</h4><p>${concepts.axis[0]}</p><p>${concepts.axis[1]}</p></div><div class="concept-block"><h4>${state.lang === "ja" ? "極を中心にする" : "Centering a pole"}</h4><p>${concepts.pole[0]}</p><p>${concepts.pole[1]}</p></div>`; $("projection-help").classList.toggle("open", projectionHelpOpen); $("close-help").addEventListener("click", () => { projectionHelpOpen = false; renderProjectionHelp(); }); }
function setLanguage() { const t = labels[state.lang]; document.documentElement.lang = state.lang === "ja" ? "ja" : "en"; document.title = t.title; document.querySelectorAll<HTMLElement>("[data-label]").forEach(el => { const key = el.dataset.label as keyof typeof t; if (typeof t[key] === "string") el.textContent = t[key] as string; }); document.querySelectorAll<HTMLInputElement>("[data-label-placeholder]").forEach(input => { input.placeholder = t[input.dataset.labelPlaceholder as keyof typeof t] as string; }); document.querySelectorAll<HTMLOptionElement>("[data-projection]").forEach(option => { option.textContent = t.projectionNames[option.dataset.projection as ProjectionName]; }); $("guide").textContent = t.guide; refreshCityOptions(); renderProjectionHelp(); render(); }
function syncInput() { state.lng = Number($(HTMLInputElement, "lng").value); state.lat = Number($(HTMLInputElement, "lat").value); state.roll = Number($(HTMLInputElement, "roll").value); state.scale = Number($(HTMLInputElement, "scale").value); updateProjection(); render(); }
function resize() { const box = $("map-container").getBoundingClientRect(), dpr = window.devicePixelRatio || 1; width = Math.max(1, box.width); height = Math.max(1, box.height); canvas.width = Math.round(width * dpr); canvas.height = Math.round(height * dpr); canvas.style.width = `${width}px`; canvas.style.height = `${height}px`; context.setTransform(dpr, 0, 0, dpr, 0, 0); updateProjection(); render(); }
function exportPng() { const link = document.createElement("a"); link.download = `map-orientation-studio-${state.projection}.png`; link.href = canvas.toDataURL("image/png"); link.click(); }

function buildUI() {
  document.querySelector<HTMLDivElement>("#app")!.innerHTML = `<aside id="sidebar"><h1 data-label="title"></h1><div class="version">v0.3.0</div><section><div class="title-row"><h2 data-label="projection"></h2><button id="projection-info" class="info-button" type="button">i</button></div><select id="projection"><option data-projection="azimuthal" value="azimuthal"></option><option data-projection="mercator" value="mercator"></option><option data-projection="equalEarth" value="equalEarth"></option><option data-projection="orthographic" value="orthographic"></option><option data-projection="equirectangular" value="equirectangular"></option></select></section><section><h2 data-label="center"></h2><input id="city-search" type="search" data-label-placeholder="search" placeholder=""><select id="city"></select><label class="compact-select"><span data-label="cityMode"></span><select id="city-mode"><option value="major" data-label="majorCities"></option><option value="all" data-label="allCities"></option></select></label><label class="compact-select"><span data-label="compareCity"></span><select id="city-compare"></select></label><div id="comparison" class="readout"></div></section><section><h2 data-label="telemetry"></h2><label><span data-label="lng"></span><input id="lng" type="number" step=".01"></label><label><span data-label="lat"></span><input id="lat" type="number" step=".01"></label><label><span data-label="roll"></span><input id="roll" type="number" step=".1"></label><label><span data-label="scale"></span><input id="scale" type="number" step="1"></label><div id="distance" class="readout"></div></section><section><h2 data-label="layers"></h2>${(["borders", "cities", "standardGrid", "axisGrid", "axis", "circles", "routes", "tissot"] as LayerKey[]).map(k => `<label class="toggle"><span data-label="${k}"></span><input id="layer-${k}" type="checkbox" checked><span class="switch"></span></label>`).join("")}</section><section><h2 data-label="theme"></h2><select id="theme"><option value="classic">Classic</option><option value="cyber">Cyber</option><option value="military">Military</option><option value="nature">Nature</option><option value="paper">Paper</option></select></section><footer><button id="export" data-label="export"></button><button id="lang">English / 日本語</button></footer></aside><main id="map-container"><div id="status" data-label="loading"></div><div id="guide"></div><aside id="projection-help"></aside></main>`;
  ( $("projection") as HTMLSelectElement).value = state.projection; ($( "theme") as HTMLSelectElement).value = state.theme;
  refreshCityOptions(); ($( "city-mode") as HTMLSelectElement).value = cityMode;
  $("projection").addEventListener("change", e => { state.projection = (e.target as HTMLSelectElement).value as ProjectionName; updateProjection(); render(); });
  $("projection-info").addEventListener("click", () => { projectionHelpOpen = !projectionHelpOpen; renderProjectionHelp(); });
  $("city").addEventListener("change", e => { [state.lng, state.lat] = JSON.parse((e.target as HTMLSelectElement).value); updateProjection(); render(); });
  $("city-compare").addEventListener("change", e => { compareCoord = JSON.parse((e.target as HTMLSelectElement).value); render(); });
  $("city-search").addEventListener("input", e => { cityQuery = (e.target as HTMLInputElement).value; refreshCityOptions(); });
  $("city-mode").addEventListener("change", e => { cityMode = (e.target as HTMLSelectElement).value as "major" | "all"; refreshCityOptions(); render(); });
  ["lng", "lat", "roll", "scale"].forEach(id => $(id).addEventListener("change", syncInput));
  (Object.keys(state.layers) as LayerKey[]).forEach(key => { ($(`layer-${key}`) as HTMLInputElement).checked = state.layers[key]; $(`layer-${key}`).addEventListener("change", e => { state.layers[key] = (e.target as HTMLInputElement).checked; render(); }); });
  $("theme").addEventListener("change", e => { state.theme = (e.target as HTMLSelectElement).value as ThemeName; render(); });
  $("export").addEventListener("click", exportPng); $("lang").addEventListener("click", () => { state.lang = state.lang === "ja" ? "en" : "ja"; setLanguage(); });
  $("map-container").appendChild(canvas); canvas.addEventListener("pointerdown", e => { activePointers.set(e.pointerId, { x: e.clientX, y: e.clientY }); pointerStart = activePointers.size === 1 ? { x: e.clientX, y: e.clientY } : null; if (activePointers.size === 2) { pinchStartDistance = pointerDistance(); pinchStartScale = state.scale; } canvas.setPointerCapture(e.pointerId); });
  canvas.addEventListener("pointermove", e => { const coords = projection?.invert?.([e.offsetX, e.offsetY]) as [number, number] | null; updateReadout(coords || undefined); if (activePointers.has(e.pointerId)) activePointers.set(e.pointerId, { x: e.clientX, y: e.clientY }); if (activePointers.size === 2 && pinchStartDistance) { state.scale = pinchStartScale * pointerDistance() / pinchStartDistance; updateProjection(); render(); return; } if (!pointerStart) return; const dx = e.clientX - pointerStart.x, dy = e.clientY - pointerStart.y; pointerStart = { x: e.clientX, y: e.clientY }; const sensitivity = 75 / projection.scale(); if (e.shiftKey) state.roll += dx * .6; else { state.lng += dx * sensitivity; state.lat -= dy * sensitivity; } updateProjection(); render(); });
  const endPointer = (e: PointerEvent) => { activePointers.delete(e.pointerId); pointerStart = null; if (activePointers.size < 2) pinchStartDistance = null; }; canvas.addEventListener("pointerup", endPointer); canvas.addEventListener("pointercancel", endPointer); canvas.addEventListener("wheel", e => { e.preventDefault(); state.scale *= e.deltaY > 0 ? .9 : 1.1; updateProjection(); render(); }, { passive: false });
}

async function init() { restoreState(); buildUI(); setLanguage(); try { const data: any = await d3.json("https://unpkg.com/world-atlas@2.0.2/countries-110m.json"); world = feature(data, data.objects.land); borders = mesh(data, data.objects.countries, (a: any, b: any) => a !== b); $("status").remove(); resize(); } catch { $("status").textContent = labels[state.lang].error; } window.addEventListener("resize", resize); }
init();
